name: use_in_case
description: An extendable library that provides functionality for use cases
version: 1.2.1
repository: https://github.com/FelixCpp/use_in_case

environment:
  sdk: ^3.0.0

dependencies:
  dartz: ^0.10.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0