name: use_in_case
description: An extendable library that provides functionality for use cases
version: 1.0.0
repository: https://github.com/FelixCpp/use_in_case

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.14.0
  dartz: ^0.10.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.4.9
  coverage: ^1.8.0
