name: use_in_case
description: >-
  Have you ever tried to follow a clean-architecture approach in your Project?
  If so, you probably have a lot of UseCases. This package will help you to use
  them in a more readable way. It's a simple package that provides a set of
  classes and functions to help you configuring your UseCases in a more
  flexible and readable way. It is designed to be used in combination with
  Business-Logic-Components (BLoC).

version: 1.4.0
repository: https://github.com/FelixCpp/use_in_case

topics:
  - dart
  - flutter
  - bloc
  - utility
  - clean-architecture

environment:
  sdk: ^3.0.0

dependencies:
  dartz: ^0.10.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0