name: use_in_case
description: A Dart package that provides a set of functionality to help you write usecases.
version: 1.4.3
repository: https://github.com/FelixCpp/use_in_case

topics:
  - dart
  - utility

environment:
  sdk: ^3.0.0

dependencies:
  dartz: ^0.10.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0