name: uic_interactor
description: A package to write usecases (specifically interactors) in dart.
version: 1.0.0
repository: https://github.com/FelixCpp/use_in_case
publish_to: 'none'

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  meta: any
  freezed_annotation: any

dev_dependencies:
  build_runner: ^2.4.8
  lints: ^3.0.0
  test: ^1.24.0
  freezed: any
