name: uic_interactor_profiler
description: Profiling the duration of the calls to invocation events.
version: 1.0.0
repository: https://github.com/FelixCpp/use_in_case
publish_to: 'none'

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  uic_interactor:
    path: ../uic-interactor
  freezed_annotation:

dev_dependencies:
  lints:
  test:
  freezed:
  build_runner:
