name: uic_interactor_busy_state_listener
description: This package provides functionality to add a receiver for status changes of an interactor.
version: 1.0.0
publish_to: 'none'
repository: https://github.com/FelixCpp/use_in_case

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  uic_interactor:
    path: ../uic-interactor

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.1
